[variables]
NPM_CONFIG_CACHE = "/root/.npm"

[phases.install]
cmds = ["npm ci --cache $NPM_CONFIG_CACHE"]
cacheDirectories = ["/root/.npm"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
